title:              Blog
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://vitalibondar.github.io

author:
  name:             Vitali Bondar
  url:              https://twitter.com/vitalikmp
  email:            vitaliy.bondar@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
