title:              Blog
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://YourName.github.io

author:
  name:             The_Kite_Runner
  url:              https://twitter.com/YourName
  email:            guofuzi123@sina.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
