title:              Qauland's Sandbox
tagline:            Not a beautiful sandbox
description:        [beep]
url:                http://qauland.github.io

author:
  name:             Qauland
  url:              https://twitter.com/qauland
  email:            ktbstsn@outlook.co.id

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
