title:              Апостолски мисли
tagline:            
description:        Просто една онлайн тетрадка.
url:                http://gpbak.github.io/bg

author:
  name:             gpbak
  url:              http://gpbak.github.io/bg
  email:            gpbak@opmbx.org

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-tactile
